<template>
  <div class="faq-view">
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
    <h2 class="faq-view__title">Lorem ipsum dolor sit amet</h2>
    <p class="faq-view__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit arcu eu eros viverra, bibendum imperdiet justo molestie. Fusce a purus convallis, cursus augue vel, consequat purus. Quisque ac luctus erat. Cras et blandit ante, nec venenatis tortor. Nam massa dui, blandit nec lectus sed, lobortis finibus ex. In sit amet ipsum vitae ante vehicula tristique. Aliquam et blandit ipsum. Sed congue malesuada nunc. Quisque posuere tincidunt nibh, et imperdiet orci vestibulum eget. Nulla congue facilisis dui, ut tempus lorem facilisis vel. Sed sit amet lorem ante. Curabitur aliquet nisi quis elit rhoncus, ut varius nisi varius. Sed fringilla, eros ut malesuada rhoncus, felis libero pellentesque justo, in commodo ex diam ut orci. Morbi pellentesque vehicula massa non consequat. Donec et lacus sed leo consectetur commodo.</p>
  </div>
</template>

<style lang="scss" scoped>
.faq-view {
  margin: 2rem;

  &__title {
    text-align: left;
  }

  &__content {
    text-align: justify;
  }
}
</style>